### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/rl-noisemodel#1]
Let me write down a todo list for this task:
- [x] implement a DQN architecture, some examples I have used for [this paper](https://arxiv.org/abs/1903.09644) are [here](https://github.com/JetsGame/GroomRL).
- [ ] decide how to merge the RL actions with parameter fit
- [ ] collect data using simulation and/or real data from the 1q
- [x] build a cross-validation toolkit in order to estimate the stability and generalization power of this model.
