### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Simone-Bordoni** [qiboteam/rl-noisemodel#26]
- [x] Multiple qubit circuits #25 
- [x] Choice of noisy gates to reproduce noise
- [x] Discrete actions vs continuous noise parameter choice #29 
- [x] Generalization tests #36 
- [ ] Implementation on real 1q data #35 
- [ ] benchmark with RB and qibo noise simulator
- [ ] 3q IBM hardware
- [ ] Benchmark with qiskit noise model
